sonar.projectKey=ita-social-projects-oit-client
sonar.organization=ita-social-projects
sonar.exclusions=**/*.test.tsx
sonar.coverage.exclusions=**/*.test.tsx,**/*.model.ts,**/*.type.ts
sonar.cpd.exclusions=**/*.test.tsx
sonar.javascript.lcov.reportPaths=./coverage/lcov.info