name: Lint, build and test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches: [ dev ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint
      - name: Run build
        run: pnpm run build
      - name: Run tests
        run: pnpm run test